/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Persistência.conexaomysql;
import Variaveis.Variaveis;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Skalybuhr
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    //Variáveis para conexão com o banco de dados
    Connection conmysql;
    PreparedStatement psmt;
    ResultSet rs;
    
    public Login() throws ClassNotFoundException {
        initComponents();
        
        //Conexão com o banco de dados
        conmysql = conexaomysql.conectabdmysql();
    }
    
    //Métodos
    private void Logar(){
        String sql = "Select * from "+Variaveis.TB_LOGIN+" where login = ? and senha = ?";
        
        try {
            psmt = conmysql.prepareStatement(sql);
            psmt.setString(1, jt_Usuario_Login.getText());
            psmt.setString(2, jp_Senha_Login.getText());
            rs = psmt.executeQuery();
            if(rs.next()){
                Variaveis.USUARIO_SISTEMA = jt_Usuario_Login.getText();
                Tela_Principal tp = new Tela_Principal();
                tp.setEnabled(true);
                tp.setVisible(true);
                System.out.println("Logando...");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha inválido, tente novamente!");
            }
        } catch (SQLException error) {
            System.out.println("try do login: "+error);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_Usuario = new javax.swing.JLabel();
        jl_Senha = new javax.swing.JLabel();
        jt_Usuario_Login = new javax.swing.JTextField();
        jp_Senha_Login = new javax.swing.JPasswordField();
        jb_conectar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SysPet", 0, 0, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jl_Usuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Usuario.setText("Usuário:");

        jl_Senha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_Senha.setText("Senha:");

        jt_Usuario_Login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jt_Usuario_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_Usuario_LoginActionPerformed(evt);
            }
        });

        jp_Senha_Login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jb_conectar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jb_conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon_ok.png"))); // NOI18N
        jb_conectar.setText("Conectar");
        jb_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_conectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_Senha)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jl_Usuario)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jt_Usuario_Login)
                    .addComponent(jp_Senha_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_conectar)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jt_Usuario_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Senha)
                    .addComponent(jp_Senha_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jb_conectar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_Usuario_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_Usuario_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_Usuario_LoginActionPerformed

    private void jb_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_conectarActionPerformed
        // TODO add your handling code here:
        System.out.println("Está dentro do ActionPeformed do jb_Conectar");
        Logar();
    }//GEN-LAST:event_jb_conectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_conectar;
    private javax.swing.JLabel jl_Senha;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jp_Senha_Login;
    private javax.swing.JTextField jt_Usuario_Login;
    // End of variables declaration//GEN-END:variables
}
