/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.*;
import Model.Animal;
import Model.Cliente;
import Variables.Variaveis;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Skalybuhr
 */
public class Cadastro_Animal extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro_Animal
     */
    String sexo, status;
    Animal animal = new Animal();

    public Cadastro_Animal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Date dataSistema = new Date();
        jd_Anii_Data_Cad.setDate(dataSistema);

        Label_Title.setText(Variaveis.TITULO_ANIMAL);

        if (Variaveis.UPDATE == true && Variaveis.SEE == false) {
            //fetch data from database
            FetchDataAnimal();
        } else if (Variaveis.UPDATE == true && Variaveis.SEE == true) {
            jt_Ani_Nome.setEditable(false);
            jcb_Ani_Especie.setEnabled(false);
            jt_Ani_Raca.setEditable(false);
            jcb_Ani_Prop_Cod.setEditable(false);
            jcb_Ani_Prop_Cod.setEnabled(false);
            jd_Ani_Data_Nasc.setEnabled(false);
            jrb_Ani_Macho.setEnabled(false);
            jrb_Ani_Femia.setEnabled(false);
            jrb_Ani_Ativo.setEnabled(false);
            jrb_Ani_Inativo.setEnabled(false);
            jb_Ani_Salvar.setVisible(false);
            jb_Ani_Limpar.setVisible(false);
            FetchDataAnimal();
        }

        List_Id_Combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Cli_Sexo = new javax.swing.ButtonGroup();
        bg_Cli_Status = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Label_Title = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_Ani_Nome = new javax.swing.JTextField();
        jd_Ani_Data_Nasc = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrb_Ani_Macho = new javax.swing.JRadioButton();
        jrb_Ani_Femia = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrb_Ani_Ativo = new javax.swing.JRadioButton();
        jrb_Ani_Inativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jd_Anii_Data_Cad = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jcb_Ani_Especie = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jcb_Ani_Prop_Cod = new javax.swing.JComboBox<>();
        jt_Ani_Prop_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_Ani_Prop_End = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jft_Ani_Prop_Telefone = new javax.swing.JFormattedTextField();
        jft_Ani_Prop_Celular = new javax.swing.JFormattedTextField();
        jb_Ani_Cancelar = new javax.swing.JButton();
        jb_Ani_Limpar = new javax.swing.JButton();
        jb_Ani_Salvar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_Ani_Servicos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jt_Ani_Raca = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Variaveis.TITULO_CLIENTE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 77, 77));

        Label_Title.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(255, 255, 255));
        Label_Title.setText("Title");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_close_window_30.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Label_Title))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jt_Ani_Nome.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jt_Ani_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_Ani_NomeKeyPressed(evt);
            }
        });

        jd_Ani_Data_Nasc.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel6.setText("Data de Nascimento:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 0, 11))); // NOI18N

        bg_Cli_Sexo.add(jrb_Ani_Macho);
        jrb_Ani_Macho.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Ani_Macho.setText("Macho");
        jrb_Ani_Macho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Ani_MachoMouseClicked(evt);
            }
        });
        jrb_Ani_Macho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_Ani_MachoActionPerformed(evt);
            }
        });

        bg_Cli_Sexo.add(jrb_Ani_Femia);
        jrb_Ani_Femia.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Ani_Femia.setText("Fêmia");
        jrb_Ani_Femia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Ani_FemiaMouseClicked(evt);
            }
        });
        jrb_Ani_Femia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_Ani_FemiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_Ani_Macho)
                    .addComponent(jrb_Ani_Femia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_Ani_Macho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_Ani_Femia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 0, 11))); // NOI18N

        bg_Cli_Status.add(jrb_Ani_Ativo);
        jrb_Ani_Ativo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Ani_Ativo.setText("Ativo");
        jrb_Ani_Ativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Ani_AtivoMouseClicked(evt);
            }
        });
        jrb_Ani_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_Ani_AtivoActionPerformed(evt);
            }
        });

        bg_Cli_Status.add(jrb_Ani_Inativo);
        jrb_Ani_Inativo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Ani_Inativo.setText("Inativo");
        jrb_Ani_Inativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Ani_InativoMouseClicked(evt);
            }
        });
        jrb_Ani_Inativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_Ani_InativoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_Ani_Ativo)
                    .addComponent(jrb_Ani_Inativo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_Ani_Ativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_Ani_Inativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel7.setText("Data de Cadastro:");

        jd_Anii_Data_Cad.setBackground(new java.awt.Color(255, 255, 255));
        jd_Anii_Data_Cad.setEnabled(false);
        jd_Anii_Data_Cad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel9.setText("Espécie:");

        jcb_Ani_Especie.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jcb_Ani_Especie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma espécie...", "Cão", "Gato", "Ave", "Peixe", "Outros" }));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proprietário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 0, 12))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel5.setText("Cód.:");

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel10.setText("Nome:");

        jcb_Ani_Prop_Cod.setEditable(true);
        jcb_Ani_Prop_Cod.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jcb_Ani_Prop_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_Ani_Prop_CodActionPerformed(evt);
            }
        });

        jt_Ani_Prop_Nome.setEditable(false);
        jt_Ani_Prop_Nome.setBackground(new java.awt.Color(255, 255, 255));
        jt_Ani_Prop_Nome.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel2.setText("Endereço:");

        jt_Ani_Prop_End.setEditable(false);
        jt_Ani_Prop_End.setBackground(new java.awt.Color(255, 255, 255));
        jt_Ani_Prop_End.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jt_Ani_Prop_End.setToolTipText("");
        jt_Ani_Prop_End.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_Ani_Prop_EndKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel4.setText("Celular:");

        jft_Ani_Prop_Telefone.setEditable(false);
        jft_Ani_Prop_Telefone.setBackground(new java.awt.Color(255, 255, 255));
        try {
            jft_Ani_Prop_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_Ani_Prop_Telefone.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jft_Ani_Prop_Telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jft_Ani_Prop_TelefoneKeyPressed(evt);
            }
        });

        jft_Ani_Prop_Celular.setEditable(false);
        jft_Ani_Prop_Celular.setBackground(new java.awt.Color(255, 255, 255));
        try {
            jft_Ani_Prop_Celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_Ani_Prop_Celular.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jft_Ani_Prop_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jft_Ani_Prop_CelularKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jcb_Ani_Prop_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jt_Ani_Prop_Nome))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jt_Ani_Prop_End))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jft_Ani_Prop_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jft_Ani_Prop_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel4)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Ani_Prop_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Ani_Prop_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_Ani_Prop_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jft_Ani_Prop_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jft_Ani_Prop_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jb_Ani_Cancelar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Ani_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_cancel_25.png"))); // NOI18N
        jb_Ani_Cancelar.setText("Cancelar");
        jb_Ani_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Ani_CancelarActionPerformed(evt);
            }
        });

        jb_Ani_Limpar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Ani_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_broom_25.png"))); // NOI18N
        jb_Ani_Limpar.setText("Limpar");
        jb_Ani_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Ani_LimparActionPerformed(evt);
            }
        });

        jb_Ani_Salvar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Ani_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_save_25.png"))); // NOI18N
        jb_Ani_Salvar.setText("Salvar");
        jb_Ani_Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_Ani_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Ani_SalvarActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serviços Executados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI Light", 0, 12))); // NOI18N

        jt_Ani_Servicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cód.", "Serviço", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_Ani_Servicos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel11.setText("Raça:");

        jt_Ani_Raca.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jd_Ani_Data_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jd_Anii_Data_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jt_Ani_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jcb_Ani_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11)
                                .addContainerGap(156, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jt_Ani_Raca, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jb_Ani_Salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addComponent(jb_Ani_Limpar)
                                .addGap(100, 100, 100)
                                .addComponent(jb_Ani_Cancelar))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Ani_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_Ani_Especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Ani_Raca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd_Anii_Data_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd_Ani_Data_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Ani_Cancelar)
                    .addComponent(jb_Ani_Limpar)
                    .addComponent(jb_Ani_Salvar))
                .addGap(171, 171, 171))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 620));

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_Ani_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Ani_NomeKeyPressed
        // TODO add your handling code here:        
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //proximo campo
            jt_Ani_Prop_End.requestFocus();
        }
    }//GEN-LAST:event_jt_Ani_NomeKeyPressed

    private void jb_Ani_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Ani_CancelarActionPerformed
        // TODO add your handling code here:
        Variaveis.UPDATE = false;
        Variaveis.SEE = false;
        dispose();
    }//GEN-LAST:event_jb_Ani_CancelarActionPerformed

    private void jt_Ani_Prop_EndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Ani_Prop_EndKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //jft_Cli_cpf.requestFocus();
        }
    }//GEN-LAST:event_jt_Ani_Prop_EndKeyPressed

    private void jft_Ani_Prop_TelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_Ani_Prop_TelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jft_Ani_Prop_Celular.requestFocus();
        }
    }//GEN-LAST:event_jft_Ani_Prop_TelefoneKeyPressed

    private void jft_Ani_Prop_CelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_Ani_Prop_CelularKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jd_Ani_Data_Nasc.requestFocus();
        }
    }//GEN-LAST:event_jft_Ani_Prop_CelularKeyPressed

    private void jb_Ani_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Ani_LimparActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jb_Ani_LimparActionPerformed

    private void jb_Ani_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Ani_SalvarActionPerformed
        Cliente cliente = new Cliente();
        cliente.setId(Integer.parseInt(jcb_Ani_Prop_Cod.getSelectedItem().toString()));
        animal.setNome(jt_Ani_Nome.getText());
        animal.setEspecie(jcb_Ani_Especie.getSelectedItem().toString());
        animal.setRaca(jt_Ani_Raca.getText());
        animal.setProprietario(cliente);
        animal.setNascimento(jd_Ani_Data_Nasc.getDate());
        animal.setCadastro(jd_Anii_Data_Cad.getDate());
        animal.setSexo(sexo);
        animal.setStatus(status);
        System.out.println("PK: " + cliente.getId());
        if (Variaveis.UPDATE != true && Variaveis.SEE == false) {
            //Insert
            if (validation()) {
                if (AnimalDAO.Cadastrar_Animal(animal)) {
                    JOptionPane.showMessageDialog(this, "Registro salvo com suceso!");
                    //refresh the table
                    Tela_Animal ta = new Tela_Animal();
                    try {
                        ta.listarjTable();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Cadastro_Animal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao salvar o registro!");
                }
            }

        } else {
            //Update
            if (AnimalDAO.Atualizar_Animal(animal)) {
                JOptionPane.showMessageDialog(this, "Registro salvo com suceso!");
                //refresh the table
                    Tela_Animal ta = new Tela_Animal();
                    try {
                        ta.listarjTable();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Cadastro_Animal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar o registro!");
            }

        }


    }//GEN-LAST:event_jb_Ani_SalvarActionPerformed

    private void jrb_Ani_MachoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Ani_MachoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrb_Ani_MachoMouseClicked

    private void jrb_Ani_FemiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Ani_FemiaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrb_Ani_FemiaMouseClicked

    private void jrb_Ani_AtivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Ani_AtivoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrb_Ani_AtivoMouseClicked

    private void jrb_Ani_InativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Ani_InativoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrb_Ani_InativoMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Variaveis.UPDATE = false;
        Variaveis.SEE = false;
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jcb_Ani_Prop_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_Ani_Prop_CodActionPerformed
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        ClienteDAO clienteDAO = new ClienteDAO();
        cliente.setId(Integer.parseInt(jcb_Ani_Prop_Cod.getSelectedItem().toString()));
        for (Cliente c : clienteDAO.Buscar_Cliente(cliente.getId())) {
            jt_Ani_Prop_Nome.setText(c.getNome());
            jt_Ani_Prop_End.setText(c.getEndereco());
            jft_Ani_Prop_Telefone.setText(c.getTelefone());
            jft_Ani_Prop_Celular.setText(c.getCelular());
        }
    }//GEN-LAST:event_jcb_Ani_Prop_CodActionPerformed

    private void jrb_Ani_MachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_Ani_MachoActionPerformed
        // TODO add your handling code here:
        sexo = "Macho";
    }//GEN-LAST:event_jrb_Ani_MachoActionPerformed

    private void jrb_Ani_FemiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_Ani_FemiaActionPerformed
        // TODO add your handling code here:
        sexo = "Femia";
    }//GEN-LAST:event_jrb_Ani_FemiaActionPerformed

    private void jrb_Ani_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_Ani_AtivoActionPerformed
        // TODO add your handling code here:
        status = "Ativo";
    }//GEN-LAST:event_jrb_Ani_AtivoActionPerformed

    private void jrb_Ani_InativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_Ani_InativoActionPerformed
        // TODO add your handling code here:
        status = "Inativo";
    }//GEN-LAST:event_jrb_Ani_InativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Animal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro_Animal dialog = new Cadastro_Animal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //Methods
    private void clean() {
        //TextFields
        jt_Ani_Nome.setText(null);
        jt_Ani_Prop_End.setText(null);
        jt_Ani_Prop_Nome.setText(null);
        jt_Ani_Raca.setText(null);
        //FormattedTextFiels
        jft_Ani_Prop_Celular.setText(null);
        jft_Ani_Prop_Telefone.setText(null);
        //DateChoose
        jd_Ani_Data_Nasc.setDate(null);
        //ComboBox
        jcb_Ani_Especie.setSelectedIndex(0);
        jcb_Ani_Prop_Cod.setSelectedIndex(0);

    }

    private void List_Id_Combobox() {
        ClienteDAO clienteDAO = new ClienteDAO();

        for (Cliente c : clienteDAO.Id_Cliente()) {
            jcb_Ani_Prop_Cod.addItem(c.getId().toString());
        }
    }

    private boolean validation() {
        ImageIcon icon = new ImageIcon();
        icon.getClass().getResource("//Images/icons_cancel_25.png");
        String title = "Campo Obrigatório";
        if (jt_Ani_Nome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo nome vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else if (jt_Ani_Raca.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo raça vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else if (jcb_Ani_Especie.getSelectedIndex() < 1) {
            JOptionPane.showMessageDialog(null, "Selecione uma espécie!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else if (jd_Ani_Data_Nasc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo data de nascimento vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else if (sexo == null) {
            JOptionPane.showMessageDialog(null, "Sexo não selecionado!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else if (status == null) {
            JOptionPane.showMessageDialog(null, "Status não selecionado!", title, JOptionPane.ERROR_MESSAGE, icon);
            return false;
        } else {
            System.out.println("Sending...");
            return true;

        }
    }

    public void FetchDataAnimal() {
        AnimalDAO animalDAO = new AnimalDAO();
        Cliente cliente = new Cliente();
        for (Animal a : animalDAO.Buscar_Animal_Id(Variaveis.ID)) {
            animal.setId(a.getId());
            jt_Ani_Nome.setText(a.getNome());
            jcb_Ani_Especie.setSelectedItem(a.getEspecie());
            jt_Ani_Raca.setText(a.getRaca());
            jcb_Ani_Prop_Cod.setSelectedItem(a.getProprietario().getId());
            jd_Ani_Data_Nasc.setDate(a.getNascimento());
            if (a.getSexo().equals("Macho")) {
                jrb_Ani_Macho.setSelected(true);
                sexo = "Macho";
            } else {
                jrb_Ani_Femia.setSelected(true);
                sexo = "Femia";
            }
            if (a.getStatus().equals("Ativo")) {
                jrb_Ani_Ativo.setSelected(true);
                status = "Ativo";
            } else {
                jrb_Ani_Inativo.setSelected(true);
                status = "Inativo";
            }
            jd_Anii_Data_Cad.setDate(a.getCadastro());
        }
        //jcb_Ani_Especie.getModel().setSelectedItem(animal.getEspecie());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Title;
    private javax.swing.ButtonGroup bg_Cli_Sexo;
    private javax.swing.ButtonGroup bg_Cli_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Ani_Cancelar;
    private javax.swing.JButton jb_Ani_Limpar;
    private javax.swing.JButton jb_Ani_Salvar;
    private javax.swing.JComboBox<String> jcb_Ani_Especie;
    private javax.swing.JComboBox<String> jcb_Ani_Prop_Cod;
    private com.toedter.calendar.JDateChooser jd_Ani_Data_Nasc;
    private com.toedter.calendar.JDateChooser jd_Anii_Data_Cad;
    private javax.swing.JFormattedTextField jft_Ani_Prop_Celular;
    private javax.swing.JFormattedTextField jft_Ani_Prop_Telefone;
    private javax.swing.JRadioButton jrb_Ani_Ativo;
    private javax.swing.JRadioButton jrb_Ani_Femia;
    private javax.swing.JRadioButton jrb_Ani_Inativo;
    private javax.swing.JRadioButton jrb_Ani_Macho;
    private javax.swing.JTextField jt_Ani_Nome;
    private javax.swing.JTextField jt_Ani_Prop_End;
    private javax.swing.JTextField jt_Ani_Prop_Nome;
    private javax.swing.JTextField jt_Ani_Raca;
    private javax.swing.JTable jt_Ani_Servicos;
    // End of variables declaration//GEN-END:variables
}
