/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.ClienteDAO;
import Model.Cliente;
import Variables.Variaveis;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Skalybuhr
 */
public class Cadastro_Cliente extends javax.swing.JDialog {

    /**
     * Creates new form Cadastro_Cliente
     */
    Cliente cliente = new Cliente();
    String sexo, status;

    public Cadastro_Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        Date dataSistema = new Date();
        jd_Cli_Data_Cad.setDate(dataSistema);
        
        Label_Title.setText(Variaveis.TITULO_CLIENTE);
        
        //System.out.println("Id: "+Variaveis.ID+" + Status: "+Variaveis.UPDATE);
        //nome, endereco, cpf, telefone, celular, nascimento, sexo, status, cadastro
        
        if (Variaveis.UPDATE == true) {
            //fetch data from database
            ClienteDAO clienteDAO = new ClienteDAO();
            for (Cliente c : clienteDAO.Buscar_Cliente(Variaveis.ID)) {
                jt_Cli_Nome.setText(c.getNome());
                jt_Cli_End.setText(c.getEndereco());
                jft_Cli_cpf.setText(c.getCpf());
                jft_Cli_Telefone.setText(c.getTelefone());
                jft_Cli_Celular.setText(c.getCelular());
                jd_Cli_Data_Nasc.setDate(c.getNascimento());
                sexo = c.getSexo();
                status = c.getStatus();
                jd_Cli_Data_Cad.setDate(c.getCadastro());

            }
            
            if(sexo.equals("Masculino")){
                jrb_Cli_Masc.setSelected(true);
            }else{
                jrb_Cli_Fem.setSelected(true);
            }
            if(status.equals("Ativo")){
                jrb_Cli_ativo.setSelected(true);
            }else{
                jrb_Cli_inativo.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Cli_Sexo = new javax.swing.ButtonGroup();
        bg_Cli_Status = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        Label_Title = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_Cli_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_Cli_End = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jft_Cli_Telefone = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jft_Cli_Celular = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jft_Cli_cpf = new javax.swing.JFormattedTextField();
        jd_Cli_Data_Nasc = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrb_Cli_Masc = new javax.swing.JRadioButton();
        jrb_Cli_Fem = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jrb_Cli_ativo = new javax.swing.JRadioButton();
        jrb_Cli_inativo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jd_Cli_Data_Cad = new com.toedter.calendar.JDateChooser();
        jb_Cli_Salvar = new javax.swing.JButton();
        jb_Cli_Limpar = new javax.swing.JButton();
        jb_Cli_Cancelar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Variaveis.TITULO_CLIENTE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 77, 77));

        Label_Title.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 18)); // NOI18N
        Label_Title.setForeground(new java.awt.Color(255, 255, 255));
        Label_Title.setText("Title");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_close_window_30.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 476, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Label_Title))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jt_Cli_Nome.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jt_Cli_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_Cli_NomeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel2.setText("Endereço:");

        jt_Cli_End.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jt_Cli_End.setToolTipText("");
        jt_Cli_End.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_Cli_EndKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel3.setText("Telefone:");

        try {
            jft_Cli_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_Cli_Telefone.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jft_Cli_Telefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jft_Cli_TelefoneKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel4.setText("Celular:");

        try {
            jft_Cli_Celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####.####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_Cli_Celular.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jft_Cli_Celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jft_Cli_CelularKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel5.setText("CPF:");

        try {
            jft_Cli_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jft_Cli_cpf.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N
        jft_Cli_cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jft_Cli_cpfKeyPressed(evt);
            }
        });

        jd_Cli_Data_Nasc.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel6.setText("Data de Nascimento:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 0, 11))); // NOI18N

        bg_Cli_Sexo.add(jrb_Cli_Masc);
        jrb_Cli_Masc.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Cli_Masc.setText("Masculino");
        jrb_Cli_Masc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Cli_MascMouseClicked(evt);
            }
        });

        bg_Cli_Sexo.add(jrb_Cli_Fem);
        jrb_Cli_Fem.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Cli_Fem.setText("Feminino");
        jrb_Cli_Fem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Cli_FemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_Cli_Masc)
                    .addComponent(jrb_Cli_Fem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_Cli_Masc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_Cli_Fem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei Light", 0, 11))); // NOI18N

        bg_Cli_Status.add(jrb_Cli_ativo);
        jrb_Cli_ativo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Cli_ativo.setText("Ativo");
        jrb_Cli_ativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Cli_ativoMouseClicked(evt);
            }
        });

        bg_Cli_Status.add(jrb_Cli_inativo);
        jrb_Cli_inativo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 11)); // NOI18N
        jrb_Cli_inativo.setText("Inativo");
        jrb_Cli_inativo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrb_Cli_inativoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_Cli_ativo)
                    .addComponent(jrb_Cli_inativo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_Cli_ativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_Cli_inativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel7.setText("Data de Cadastro:");

        jd_Cli_Data_Cad.setBackground(new java.awt.Color(255, 255, 255));
        jd_Cli_Data_Cad.setEnabled(false);
        jd_Cli_Data_Cad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 11)); // NOI18N

        jb_Cli_Salvar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Cli_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_save_25.png"))); // NOI18N
        jb_Cli_Salvar.setText("Salvar");
        jb_Cli_Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jb_Cli_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Cli_SalvarActionPerformed(evt);
            }
        });

        jb_Cli_Limpar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Cli_Limpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_broom_25.png"))); // NOI18N
        jb_Cli_Limpar.setText("Limpar");
        jb_Cli_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Cli_LimparActionPerformed(evt);
            }
        });

        jb_Cli_Cancelar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jb_Cli_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_cancel_25.png"))); // NOI18N
        jb_Cli_Cancelar.setText("Cancelar");
        jb_Cli_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Cli_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jt_Cli_End, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jt_Cli_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(197, 197, 197)
                            .addComponent(jLabel3)
                            .addGap(114, 114, 114)
                            .addComponent(jLabel4))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jft_Cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(jft_Cli_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jft_Cli_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jb_Cli_Salvar))
                                    .addGap(84, 84, 84)
                                    .addComponent(jb_Cli_Limpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jb_Cli_Cancelar))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jd_Cli_Data_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(24, 24, 24)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jd_Cli_Data_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jt_Cli_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jt_Cli_End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jft_Cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jft_Cli_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jft_Cli_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd_Cli_Data_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd_Cli_Data_Cad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Cli_Salvar)
                    .addComponent(jb_Cli_Limpar)
                    .addComponent(jb_Cli_Cancelar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 340));

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jt_Cli_NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Cli_NomeKeyPressed
        // TODO add your handling code here:        
        if (evt.getKeyCode() == evt.VK_ENTER) {
            //proximo campo
            jt_Cli_End.requestFocus();
        }
    }//GEN-LAST:event_jt_Cli_NomeKeyPressed

    private void jb_Cli_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Cli_CancelarActionPerformed
        // TODO add your handling code here:
        Variaveis.UPDATE = false;
        dispose();
    }//GEN-LAST:event_jb_Cli_CancelarActionPerformed

    private void jt_Cli_EndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Cli_EndKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jft_Cli_cpf.requestFocus();
        }
    }//GEN-LAST:event_jt_Cli_EndKeyPressed

    private void jft_Cli_cpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_Cli_cpfKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jft_Cli_Telefone.requestFocus();
        }
    }//GEN-LAST:event_jft_Cli_cpfKeyPressed

    private void jft_Cli_TelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_Cli_TelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jft_Cli_Celular.requestFocus();
        }
    }//GEN-LAST:event_jft_Cli_TelefoneKeyPressed

    private void jft_Cli_CelularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jft_Cli_CelularKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jd_Cli_Data_Nasc.requestFocus();
        }
    }//GEN-LAST:event_jft_Cli_CelularKeyPressed

    private void jb_Cli_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Cli_LimparActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jb_Cli_LimparActionPerformed

    private void jb_Cli_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Cli_SalvarActionPerformed
        
        cliente.setNome(jt_Cli_Nome.getText());
        cliente.setEndereco(jt_Cli_End.getText());
        cliente.setCpf(jft_Cli_cpf.getText());
        cliente.setTelefone(jft_Cli_Telefone.getText());
        cliente.setCelular(jft_Cli_Celular.getText());
        cliente.setNascimento(jd_Cli_Data_Nasc.getDate());
        cliente.setSexo(sexo);
        cliente.setStatus(status);
        cliente.setCadastro(jd_Cli_Data_Cad.getDate());

        //System.out.println("Nome: " + cliente.getNome() + " - Classe Cadastro");
        //System.out.println("Nascimento: " + cliente.getNascimento() + " - Classe Cadastro");

        if (Variaveis.UPDATE != true) {
            //Insert
            try {
                // TODO add your handling code here:
                validation();
            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Cadastro_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else{
            //Update
            ClienteDAO clienteDAO = new ClienteDAO();
            Tela_Cliente tc = new Tela_Cliente();
            cliente.setId(Variaveis.ID);
            if(clienteDAO.Atualizar_Cliente(cliente)){
                JOptionPane.showMessageDialog(this, "Atualizado com sucesso!");
                try {
                    tc.listarjTable();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Cadastro_Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
            
        }
        
        

    }//GEN-LAST:event_jb_Cli_SalvarActionPerformed

    private void jrb_Cli_MascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Cli_MascMouseClicked
        // TODO add your handling code here:
        sexo = "Masculino";
    }//GEN-LAST:event_jrb_Cli_MascMouseClicked

    private void jrb_Cli_FemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Cli_FemMouseClicked
        // TODO add your handling code here:
        sexo = "Feminino";
    }//GEN-LAST:event_jrb_Cli_FemMouseClicked

    private void jrb_Cli_ativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Cli_ativoMouseClicked
        // TODO add your handling code here:
        status = "Ativo";
    }//GEN-LAST:event_jrb_Cli_ativoMouseClicked

    private void jrb_Cli_inativoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrb_Cli_inativoMouseClicked
        // TODO add your handling code here:
        status = "Inativo";
    }//GEN-LAST:event_jrb_Cli_inativoMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Variaveis.UPDATE = false;
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro_Cliente dialog = new Cadastro_Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    //Methods
    private void clean() {
        jt_Cli_Nome.setText(null);
        jt_Cli_End.setText(null);
        jft_Cli_cpf.setText(null);
        jft_Cli_Telefone.setText(null);
        jft_Cli_Celular.setText(null);
        jd_Cli_Data_Nasc.setDate(null);
    }

    private void validation() throws ClassNotFoundException {
        ImageIcon icon = new ImageIcon();
        icon.getClass().getResource("//Images/icons_cancel_25.png");
        String title = "Campo Obrigatório";
        if (jt_Cli_Nome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo nome vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (jt_Cli_End.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo endereço vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (jft_Cli_cpf.getText().equals("   .   .   -  ")) {
            JOptionPane.showMessageDialog(null, "Campo cpf vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (jft_Cli_Telefone.getText().equals("(  )     .    ")) {
            JOptionPane.showMessageDialog(null, "Campo telefone vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (jft_Cli_Celular.getText().equals("(  )      .    ")) {
            JOptionPane.showMessageDialog(null, "Campo celular vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (jd_Cli_Data_Nasc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Campo data de nascimento vazio!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (sexo == null) {
            JOptionPane.showMessageDialog(null, "Sexo não selecionado!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else if (status == null) {
            JOptionPane.showMessageDialog(null, "Status não selecionado!", title, JOptionPane.ERROR_MESSAGE, icon);
        } else {
            System.out.println("Sending...");
            
            ClienteDAO clienteDAO = new ClienteDAO();
            
            if(clienteDAO.Cadastrar_Cliente(cliente)){                
                JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                clean();
            } else {
                JOptionPane.showMessageDialog(this, "Erro!");
            }
            

        }
    }  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Title;
    private javax.swing.ButtonGroup bg_Cli_Sexo;
    private javax.swing.ButtonGroup bg_Cli_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jb_Cli_Cancelar;
    private javax.swing.JButton jb_Cli_Limpar;
    private javax.swing.JButton jb_Cli_Salvar;
    private com.toedter.calendar.JDateChooser jd_Cli_Data_Cad;
    private com.toedter.calendar.JDateChooser jd_Cli_Data_Nasc;
    private javax.swing.JFormattedTextField jft_Cli_Celular;
    private javax.swing.JFormattedTextField jft_Cli_Telefone;
    private javax.swing.JFormattedTextField jft_Cli_cpf;
    private javax.swing.JRadioButton jrb_Cli_Fem;
    private javax.swing.JRadioButton jrb_Cli_Masc;
    private javax.swing.JRadioButton jrb_Cli_ativo;
    private javax.swing.JRadioButton jrb_Cli_inativo;
    private javax.swing.JTextField jt_Cli_End;
    private javax.swing.JTextField jt_Cli_Nome;
    // End of variables declaration//GEN-END:variables
}
