/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Variables.Variaveis;
/**
 *
 * @author Skalybuhr
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    
    
    public Tela_Principal() {
        initComponents();
        //Iniciar com a tela inteira
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Cliente = new javax.swing.JMenu();
        jmi_Cliente = new javax.swing.JMenuItem();
        jmi_animal = new javax.swing.JMenuItem();
        jMenu_Gestao = new javax.swing.JMenu();
        jmi_Funcionarios = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmi_Cargos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu_Movimentos = new javax.swing.JMenu();
        jm_Caixa = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jm_Estoque = new javax.swing.JMenu();
        jmi_Produtos = new javax.swing.JMenuItem();
        jmi_Categ_Prod = new javax.swing.JMenuItem();
        jmi_Venda = new javax.swing.JMenuItem();
        jMenu_Sair = new javax.swing.JMenu();
        jmi_Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(Variaveis.NOME_SISTEMA+" - Usuário: "+Variaveis.USUARIO_SISTEMA);
        setName(""); // NOI18N

        jDesktopPane.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jMenu_Cliente.setText("Cliente");
        jMenu_Cliente.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N

        jmi_Cliente.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jmi_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_customer_25.png"))); // NOI18N
        jmi_Cliente.setText("Cliente");
        jmi_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_ClienteActionPerformed(evt);
            }
        });
        jMenu_Cliente.add(jmi_Cliente);

        jmi_animal.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jmi_animal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_animal_25.png"))); // NOI18N
        jmi_animal.setText("Animal");
        jMenu_Cliente.add(jmi_animal);

        jMenuBar1.add(jMenu_Cliente);

        jMenu_Gestao.setText("Gestão");
        jMenu_Gestao.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N

        jmi_Funcionarios.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jmi_Funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_employee_25.png"))); // NOI18N
        jmi_Funcionarios.setText("Funcionários");
        jMenu_Gestao.add(jmi_Funcionarios);

        jMenuItem1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_motobike_25.png"))); // NOI18N
        jMenuItem1.setText("Veículos");
        jMenu_Gestao.add(jMenuItem1);

        jmi_Cargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_carrer_25.png"))); // NOI18N
        jmi_Cargos.setText("Cargos");
        jMenu_Gestao.add(jmi_Cargos);

        jMenuItem4.setText("Fornecedores");
        jMenu_Gestao.add(jMenuItem4);

        jMenuBar1.add(jMenu_Gestao);

        jMenu_Movimentos.setText("Movimentos");
        jMenu_Movimentos.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N

        jm_Caixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_cash_register_25.png"))); // NOI18N
        jm_Caixa.setText("Caixa");

        jMenuItem2.setText("Movimentações");
        jm_Caixa.add(jMenuItem2);

        jMenuItem3.setText("Lançamentos");
        jm_Caixa.add(jMenuItem3);

        jMenu_Movimentos.add(jm_Caixa);

        jm_Estoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_cardboard_box_25.png"))); // NOI18N
        jm_Estoque.setText("Estoque");

        jmi_Produtos.setText("Produtos");
        jm_Estoque.add(jmi_Produtos);

        jmi_Categ_Prod.setText("Categoria de Produtos");
        jm_Estoque.add(jmi_Categ_Prod);

        jMenu_Movimentos.add(jm_Estoque);

        jmi_Venda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_sale_25.png"))); // NOI18N
        jmi_Venda.setText("Venda");
        jMenu_Movimentos.add(jmi_Venda);

        jMenuBar1.add(jMenu_Movimentos);

        jMenu_Sair.setText("Sair");
        jMenu_Sair.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N

        jmi_Sair.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jmi_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons_exit_sign_25.png"))); // NOI18N
        jmi_Sair.setText("Sair");
        jmi_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_SairActionPerformed(evt);
            }
        });
        jMenu_Sair.add(jmi_Sair);

        jMenuBar1.add(jMenu_Sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmi_SairActionPerformed

    private void jmi_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_ClienteActionPerformed
        // TODO add your handling code here:
        Tela_Cliente tc = new Tela_Cliente();
        jDesktopPane.add(tc);
        tc.setVisible(true);
    }//GEN-LAST:event_jmi_ClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMenu_Cliente;
    private javax.swing.JMenu jMenu_Gestao;
    private javax.swing.JMenu jMenu_Movimentos;
    private javax.swing.JMenu jMenu_Sair;
    private javax.swing.JMenu jm_Caixa;
    private javax.swing.JMenu jm_Estoque;
    private javax.swing.JMenuItem jmi_Cargos;
    private javax.swing.JMenuItem jmi_Categ_Prod;
    private javax.swing.JMenuItem jmi_Cliente;
    private javax.swing.JMenuItem jmi_Funcionarios;
    private javax.swing.JMenuItem jmi_Produtos;
    private javax.swing.JMenuItem jmi_Sair;
    private javax.swing.JMenuItem jmi_Venda;
    private javax.swing.JMenuItem jmi_animal;
    // End of variables declaration//GEN-END:variables
}
